### ISSUE TITLE
nothing happens when i do shift+1,2,3,4,5,6 ect

### ISSUE THREAD

**Issue by ghost** [slvn/isaac-destination-indicator#2]
liek the title says

**Comment by ghost** [comment]
error says:
destination_indicator/main.lua:2301: attempt to index a nil value (global 'Options')

**Comment by slvn** [comment]
@Finbean Are you on the latest version? Can you try uninstall/install the mod?

**Comment by slvn** [comment]
Ok it looks like you need to update your game. This is using the last API from the very last patch of Repentance.
